                                                             Ф.И.О.

#                                    Лабораторная работа №5

## Массивы Numpy

**1.** Сформировать одномерный массив, состоящий из n вещественных элементов co значением от -10 до 10.0. Для случайного числа y, такого, что *минимальный элемент массива < y < максимальный элемент массива*, вычислить:  
  
* произведение элементов массива, значения модуля которых больше модуля y,  
  
* сумму модулей остальных элементов.

In [4]:
import numpy as np
from random import random

n = 10
arr = np.array([random() * 20 - 10 for i in range(n)])

y = random() * (arr.max() - arr.min()) + arr.min()

print(arr, '\ny = ', y)

print(np.prod(arr[abs(arr) > abs(y)]))
print(np.sum(np.abs(arr[abs(arr) <= abs(y)])))

[ 3.49692051 -6.79029789 -4.45671038  1.0910789   3.23890132  9.45539306
  7.79103287 -1.0485248  -1.91482218 -0.14816896] 
y =  -3.211705887642758
25249.997495461736
4.202594843462579


**2.** Найти максимальный элемент в одномерном массиве x среди элементов, перед которыми стоит нулевой.

**3.** Дана целочисленная прямоугольная матрица. Определить: количество строк, не содержащих ни одного нулевого элемента, а также 
максимальное значение из чисел, встречающихся в заданной матрице более одного раза.

In [391]:
import numpy as np
from random import random

N = 8
M = 6

mtrx = np.random.randint(low=-10, high=10, size=(N, M))

print(mtrx)
lines_with_zeros = (mtrx != 0).all(1)
print('количество строк с нулями: ', len(lines_with_zeros[lines_with_zeros == False]))

elem, ind = np.unique(mtrx, return_counts=True)
print('максимальный элемент, встречающийся более одного раза: ', max(elem[ind > 1]))


[[ -4   9   8  -2   7   8]
 [ -9   7   9  -4   7   2]
 [  3   8 -10   0 -10   5]
 [  7  -6  -2   7  -3  -4]
 [ -2   1  -1   8   7  -8]
 [ -5   8   2   2   4  -4]
 [  5 -10  -5 -10  -2   6]
 [  6  -3   5   2  -6   9]]
количество строк с нулями:  1
максимальный элемент, встречающийся более одного раза:  9


**4.** Элемент матрицы называется локальным минимумом, если он строго меньше всех имеющихся у него соседей. Соседями элемента А[i,j] в матрице назовем элементы А[k,l], где i-1<=k<=i+1, j-1 < l <j+1, (k, l) != (i, j).  
Подсчитать количество локальных минимумов заданной в файле input.txt матрицы размером 10 на 10.

In [386]:
#
# НЕ ПОЛУЧАЕТСЯ
#

**5.** Определите, является ли массив магическим квадратом (суммы по всем горизонталям, вертикалям и двум диагоналям равны).

In [392]:
import numpy as np

a = np.random.randint(low=1, high=30, size=(7, 7))
b = np.array([[2, 7, 6], [9, 5, 1], [4, 3, 8]])
c = np.array([[1, 14, 15, 4], [12, 7, 6, 9], [8, 11, 10, 5], [13, 2, 3, 16]])

print(a)
print(b)
print(c)

print(np.array_equal(np.unique(a.sum(axis=1)),np.unique(a.sum(axis=0))))
print(np.array_equal(np.unique(b.sum(axis=1)),np.unique(b.sum(axis=0))))
print(np.array_equal(np.unique(c.sum(axis=1)),np.unique(c.sum(axis=0))))

[[18  6 25 20 22 24 22]
 [27 11 29 14 20  4  4]
 [12  2 13 26 12 17  5]
 [17 14 19  7 22 19 11]
 [13 14  6 25 19 26 14]
 [10 23 16 11  1 17 21]
 [14  1 23 28 14  5 12]]
[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[ 1 14 15  4]
 [12  7  6  9]
 [ 8 11 10  5]
 [13  2  3 16]]
False
True
True


**6.** Программным образом заполните массив одним из двух следующих способов.
Размерность n и m, а также номер способа заполнения вводится пользователем при запуске программы.
Результат записать в файл.

**7.** Удалите строку и столбец, на пересечении которых находится минимальный элемент массива. После этого отсортируйте столбцы массива по неубыванию минимальных элементов в них.

## Обработка исключений. Библиотека Matplotlib

**8.**	Реализовать проверку числа 35742549198872617291353508656626642567 на простоту последовательным перебором возможных делителей (не нужен эффективный алгоритм). Выполнить замер времени работы кода без обработки исключений и с ней.

**9.**	В каталоге texts сохранить не менее 10 произвольных текстов объемом не менее 500 слов.  Пользователь программным образом выбирает текст. Программа строит график частоты для 50 наиболее частотных слов текста. 

**10.**	Считать данные из текстового документа, в котором написано годовое количество осадков:

*Январь 15*

*Февраль 20*

…

*Декабрь 18*


Вывести их в форме диаграмм: обычная, горизонтальная, круговая (все виды диаграмм должны быть на одном рисунке). Сохранить получившийся рисунок в файл.


**11.** Нарисовать звёздочками зелёного цвета график кардиоиды в полярной системе координат. Добавьте легенду с заголовком «Функция» и подписью «Кардиоида» в левый верхний угол.
Угол принадлежит промежутку от 0 до 3π/2, r = 2,5. Уравнение кардиоиды: ρ = 2*r*(1 + cosφ).



**12.** Написать программу изображения графика функции y=√x. Не забывайте про то, что функция имеет значения ≥ 0. Предварительно программа запрашивает у пользователя следующую информацию:

* цвет графика (программа предлагает не менее пяти различных цветов);
* тип линии (программа предлагает не менее трех различных вариантов);
* толщину линии (программа предлагает не менее пяти различных вариантов).

Все запросы к пользователю обрабатываются с использованием обработки исключительных ситуаций. Варианты можно вводить строкой или числом (на ваш выбор).
